# Generated by Django 5.0.6 on 2024-06-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_leave_first_scan_time_leave_last_scan_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='scanned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outing',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outing',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
