# Generated by Django 5.0.6 on 2024-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_outing_scanned_count_alter_outing_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='first_scan_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='last_scan_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
