# Generated by Django 5.0.6 on 2024-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hostel',
            field=models.CharField(blank=True, choices=[('I1', 'I1'), ('I2', 'I2')], max_length=2, null=True),
        ),
    ]
